version: '3.9'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}

    networks:
      - sgsi-net
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/${ORACLE_PASSWORD}@oracle-db:1521/sgsi_pdb || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 15

  sgsi-app:
    build: .
    container_name: sgsi-app
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "5263:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SgsiDbContext=${SGSI_STRING}
    networks:
      - sgsi-net

networks:
  sgsi-net:
    driver: bridge
